INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('A1', 'He __ a student.', 'is', 'Simple present tense used to describe a state of being.'),
                                                                        ('A1', 'She __ a dog.', 'has', 'The verb "has" is used to indicate possession in the present simple tense.'),
                                                                        ('A1', 'They __ to school every day.', 'go', '"Go" is the correct verb form for the present simple tense with the subject "they".'),
                                                                        ('A1', 'We __ at home now.', 'are', '"Are" is the correct form of "to be" in the present continuous tense for the subject "we".'),
                                                                        ('A1', 'I __ reading a book.', 'am', '"Am" is used as an auxiliary verb with "I" in the present continuous tense.'),
                                                                        ('A1', 'Can you __ me?', 'help', '"Help" is used as the base form after the modal verb "can".'),
                                                                        ('A1', 'The cat __ on the mat.', 'is', '"Is" is the singular form of the verb "to be" in the present tense.'),
                                                                        ('A1', 'You __ very kind.', 'are', '"Are" is the plural form of "to be" in the present simple tense.'),
                                                                        ('A1', 'He __ his homework.', 'does', '"Does" is the correct verb form in the present simple tense for the third person singular subject "he".'),
                                                                        ('A1', 'She __ a new dress.', 'buys', '"Buys" is the correct verb form in the present simple tense for the third person singular subject "she".');


INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('A2', 'Can you ___ me the way to the station?', 'tell', '"Tell" is the correct verb to use when asking for directions.'),
                                                                        ('A2', 'I haven’t seen her ___ last week.', 'since', '"Since" is used to indicate the starting point of an action or event in the past.'),
                                                                        ('A2', 'They ___ dinner when I arrived.', 'were having', '"Were having" is the correct past continuous tense form, indicating an ongoing action in the past.'),
                                                                        ('A2', 'He was born ___ 1990.', 'in', '"In" is used with years, months, and centuries to indicate time.'),
                                                                        ('A2', 'I’d like ___ cup of tea, please.', 'a', '"A" is the correct indefinite article used before singular nouns starting with a consonant sound.'),
                                                                        ('A2', 'We will go to the beach if it ___ sunny.', 'is', '"Is" is used in the first conditional to describe a likely future event.'),
                                                                        ('A2', 'There aren’t ___ apples left in the basket.', 'any', '"Any" is used in negative sentences and questions with plural or uncountable nouns.'),
                                                                        ('A2', 'She has ___ finished her homework.', 'already', '"Already" is used to indicate that something has happened sooner than expected.'),
                                                                        ('A2', 'He doesn’t have ___ money.', 'much', '"Much" is used with uncountable nouns in negative sentences.'),
                                                                        ('A2', 'Would you like ___ more coffee?', 'some', '"Some" is used in positive sentences and offers or requests.'),
                                                                        ('A2', 'I ___ to the cinema yesterday.', 'went', '"Went" is the correct past simple form of the verb "go."');

INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('B1', 'If I ___ more time, I would travel more.', 'had', '"Had" is used in the second conditional to describe an unreal situation in the present.'),
                                                                        ('B1', 'He ___ already left when I arrived.', 'had', '"Had" is the correct past perfect tense to describe an action that happened before another action in the past.'),
                                                                        ('B1', 'I wish I ___ more money.', 'had', '"Had" is used in the subjunctive mood to express a desire for a different present situation.'),
                                                                        ('B1', 'The book ___ by the author last year.', 'was written', '"Was written" is the correct passive form in the past simple tense.'),
                                                                        ('B1', 'She said she ___ come to the party.', 'would', '"Would" is used as the future in the past tense to report what someone said about a future event.'),
                                                                        ('B1', 'I am not used to ___ up early.', 'waking', '"Waking" is a gerund form used after "used to" to indicate a habit.'),
                                                                        ('B1', 'He apologized for ___ late.', 'being', '"Being" is the gerund form used after the preposition "for" to indicate the reason for the apology.'),
                                                                        ('B1', 'She suggested ___ the meeting.', 'postponing', '"Postponing" is the gerund form used after "suggest" to indicate the action being proposed.'),
                                                                        ('B1', 'If only I ___ speak French!', 'could', '"Could" is used to express a wish or regret about a present situation.'),
                                                                        ('B1', 'By the time you arrive, I ___ finished my homework.', 'will have', '"Will have finished" is the future perfect tense used to indicate that an action will be completed before another future action.');

INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('B2', 'Not only ___ he talented, but he is also hardworking.', 'is', '"Is" is the correct verb form in the inversion structure used for emphasis.'),
                                                                        ('B2', 'He didn’t mind ___ late to finish the project.', 'staying', '"Staying" is the gerund form used after "mind" to indicate an activity someone is willing to do.'),
                                                                        ('B2', 'If she ___ harder, she would have passed the exam.', 'had studied', '"Had studied" is the correct form in the third conditional to describe an unreal past situation.'),
                                                                        ('B2', 'We need to focus on ___ the project on time.', 'completing', '"Completing" is the gerund form used after the preposition "on" to indicate the goal.'),
                                                                        ('B2', 'Despite ___ very hard, he didn’t succeed.', 'working', '"Working" is the gerund form used after "despite" to indicate the activity that took place.'),
                                                                        ('B2', 'He wishes he ___ to the meeting yesterday.', 'had gone', '"Had gone" is the past perfect tense used to express regret about a past action.'),
                                                                        ('B2', 'No sooner ___ I sit down than the phone rang.', 'did', '"Did" is used in inversion for emphasis, indicating that one action happened immediately after another.'),
                                                                        ('B2', 'I suggest that he ___ his homework before going out.', 'do', '"Do" is in the subjunctive mood, often used after verbs like "suggest."'),
                                                                        ('B2', 'If I were you, I ___ that offer.', 'would accept', '"Would accept" is the correct form in the second conditional to give advice.'),
                                                                        ('B2', 'By next year, I ___ my degree.', 'will have completed', '"Will have completed" is the future perfect tense used to indicate an action that will be finished before a certain time in the future.');

INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('C1', 'It’s high time you ___ to bed.', 'went', '"Went" is used in a subjunctive mood to express something that should have already happened.'),
                                                                        ('C1', 'She suggested that he ___ his work more carefully.', 'do', '"Do" is used in the subjunctive mood for formal suggestions or recommendations.'),
                                                                        ('C1', 'Had I known about the party, I ___ a gift.', 'would have brought', '"Would have brought" is used in the third conditional to talk about an alternative past event.'),
                                                                        ('C1', 'No sooner had he arrived ___ he was asked to leave again.', 'than', '"Than" is used with "no sooner" to indicate that one action happened immediately after another.'),
                                                                        ('C1', 'Little did they know what ___ in store for them.', 'was', '"Was" is used in an inverted sentence for emphasis, suggesting they were unaware of the future events.'),
                                                                        ('C1', 'The doctor recommended that she ___ more exercise.', 'do', '"Do" is in the subjunctive mood, often used in formal recommendations.'),
                                                                        ('C1', 'I’d rather you ___ here earlier tomorrow.', 'came', '"Came" is used in a subjunctive mood to indicate a preference for future actions.'),
                                                                        ('C1', 'Were she to find out, she ___ furious.', 'would be', '"Would be" is used in the second conditional to discuss an unlikely or hypothetical situation.'),
                                                                        ('C1', 'I wish I ___ what to say to comfort her.', 'knew', '"Knew" is used in the subjunctive mood to express a desire for a current unreal situation.'),
                                                                        ('C1', 'She acts as if she ___ everything.', 'knew', '"Knew" is used in the subjunctive mood to describe an unreal situation or something contrary to fact.');

INSERT INTO grammar_examples (grade, question, answer, commentary) VALUES
                                                                        ('C2', 'Not until the end of the film ___ who the killer was.', 'did they reveal', '"Did they reveal" is used in an inverted form for emphasis following "not until."'),
                                                                        ('C2', 'Were it not for his quick thinking, the situation ___ disastrous.', 'would have been', '"Would have been" is used in the third conditional to describe a hypothetical past outcome.'),
                                                                        ('C2', 'By no means ___ a simple task.', 'was it', '"Was it" is used in an inversion for emphasis, suggesting that the task was difficult.'),
                                                                        ('C2', 'Should you need any further information, please ___ free to contact us.', 'feel', '"Feel free" is a polite expression used to invite someone to take an action.'),
                                                                        ('C2', 'He acted as if he ___ everything about the subject.', 'knew', '"Knew" is used in the subjunctive mood to express something contrary to fact or hypothetical.'),
                                                                        ('C2', 'But for the timely intervention, they ___ the match.', 'would have lost', '"Would have lost" is used in the third conditional to talk about an alternative past outcome.'),
                                                                        ('C2', 'It was suggested that the proposal ___ reconsidered.', 'be', '"Be" is in the subjunctive mood, often used in formal suggestions or demands.'),
                                                                        ('C2', 'Had it not been for the rain, we ___ the picnic.', 'would have enjoyed', '"Would have enjoyed" is used in the third conditional to describe a hypothetical situation in the past.'),
                                                                        ('C2', 'No sooner ___ the bell rung than the class began.', 'had', '"Had" is used in an inversion for emphasis with "no sooner."'),
                                                                        ('C2', 'Hardly ___ the words leave his lips when the room erupted in laughter.', 'had', '"Had" is used in an inversion for emphasis with "hardly."');
INSERT INTO tests (grade, question, answer) VALUES
                                                ('A2', 'I need to _______ my teeth every morning. (wash, brush, drink, jump)', 'brush'),
                                                ('A2', 'She likes to _______ TV in the evening. (watch, eat, write, sleep)', 'watch'),
                                                ('A2', 'Can you _______ me the salt, please? (pass, throw, kick, sing)', 'pass'),
                                                ('A2', 'I usually _______ the bus to work. (drive, take, fly, swim)', 'take'),
                                                ('A2', 'It’s raining. Don’t forget your _______. (umbrella, sandwich, bicycle, pillow)', 'umbrella'),
                                                ('A2', 'My favorite _______ is blue. (color, animal, food, day)', 'color'),
                                                ('A2', 'I need to _______ some money from the bank. (spend, borrow, cook, plant)', 'borrow'),
                                                ('A2', 'She’s a doctor. She works in a _______. (hospital, school, restaurant, park)', 'hospital'),
                                                ('A2', 'It’s hot today. Let’s go to the _______. (beach, mountain, library, airport)', 'beach'),
                                                ('A2', 'I don’t feel well. I have a _______. (headache, birthday, holiday, sandwich)', 'headache'),
                                                ('A2', 'What _______ of music do you like? (type, color, size, weather)', 'type'),
                                                ('A2', 'Can you _______ me how to use this camera? (show, tell, give, take)', 'show'),
                                                ('A2', 'I usually _______ up at 7 o’clock in the morning. (stand, sit, wake, sleep)', 'wake'),
                                                ('A2', 'She’s _______ a blue shirt today. (wearing, eating, driving, singing)', 'wearing'),
                                                ('A2', 'We’re going to have a picnic in the _______. (park, school, hospital, airport)', 'park'),
                                                ('A2', 'I need to _______ some vegetables for dinner. (buy, sell, eat, cook)', 'buy'),
                                                ('A2', 'The museum is _______ on Mondays. (closed, open, busy, quiet)', 'closed'),
                                                ('A2', 'Can you _______ me your pen, please? (lend, borrow, give, take)', 'lend'),
                                                ('A2', 'I don’t _______ spicy food. (like, hate, love, enjoy)', 'like'),
                                                ('A2', 'She’s learning to play the _______. (guitar, car, tree, shoe)', 'guitar');
INSERT INTO tests (grade, question, answer) VALUES
                                                ('B1', 'The weather forecast says it will _______ tomorrow. (rain, raining, rained, rains)', 'rain'),
                                                ('B1', 'She’s very _______ of her new car. (proud, happy, angry, sad)', 'proud'),
                                                ('B1', 'I need to _______ my password because I forgot it. (change, exchange, alter, modify)', 'change'),
                                                ('B1', 'The movie was so _______ that I fell asleep. (boring, excited, interesting, amusing)', 'boring'),
                                                ('B1', 'Can you _______ me a favor? (do, make, give, take)', 'do'),
                                                ('B1', 'I’m looking forward _______ my vacation next month. (to, for, at, in)', 'to'),
                                                ('B1', 'She’s been working here _______ five years. (for, since, during, while)', 'for'),
                                                ('B1', 'I don’t have _______ money to buy a new phone. (enough, plenty, lot, much)', 'enough'),
                                                ('B1', 'The children were _______ when they heard the news. (excited, boring, tiring, exhausting)', 'excited'),
                                                ('B1', 'You should _______ more water every day. (drink, drinking, drank, drinks)', 'drink'),
                                                ('B1', 'I’m not sure _______ I’ll be able to attend the party. (if, when, where, what)', 'if'),
                                                ('B1', 'She _______ to be a doctor when she was young. (wanted, want, wants, wanting)', 'wanted'),
                                                ('B1', 'The book was so good that I couldn’t _______ it down. (put, take, get, make)', 'put'),
                                                ('B1', 'We need to _______ a decision by tomorrow. (make, do, take, give)', 'make'),
                                                ('B1', 'I’m sorry, but I don’t _______ with your opinion. (agree, disagree, argue, discuss)', 'agree'),
                                                ('B1', 'Can you _______ me how to get to the station? (tell, say, speak, talk)', 'tell'),
                                                ('B1', 'She’s been _______ a lot of overtime lately. (working, making, doing, taking)', 'working'),
                                                ('B1', 'I’m trying to _______ money for a new laptop. (save, spend, earn, win)', 'save'),
                                                ('B1', 'The concert was _______ out weeks ago. (sold, bought, taken, given)', 'sold'),
                                                ('B1', 'He’s very _______ at playing the guitar. (good, well, nice, fine)', 'good');
INSERT INTO tests (grade, question, answer) VALUES
                                                ('B2', 'The company has _______ a new policy to reduce waste. (implemented, implied, imparted, impacted)', 'implemented'),
                                                ('B2', 'She _______ her success to hard work and determination. (attributed, contributed, distributed, attributed)', 'attributed'),
                                                ('B2', 'The novel’s plot was so _______ that I couldn’t predict the ending. (intricate, simple, boring, predictable)', 'intricate'),
                                                ('B2', 'The government has _______ new regulations on carbon emissions. (imposed, proposed, supposed, exposed)', 'imposed'),
                                                ('B2', 'His argument was _______ and difficult to refute. (compelling, repelling, propelling, impelling)', 'compelling'),
                                                ('B2', 'The scientist’s research _______ a breakthrough in cancer treatment. (led to, resulted in, ended up, turned into)', 'led to'),
                                                ('B2', 'The company’s profits have _______ significantly over the past year. (increased, decreased, remained, fluctuated)', 'increased'),
                                                ('B2', 'The politician’s speech was _______ by frequent interruptions. (marred, marked, made, met)', 'marred'),
                                                ('B2', 'She _______ her fear of public speaking by practicing regularly. (overcame, overwhelmed, oversaw, overheard)', 'overcame'),
                                                ('B2', 'The new software has several _______ features that make it stand out. (innovative, invasive, inactive, inductive)', 'innovative'),
                                                ('B2', 'The documentary _______ light on the plight of endangered species. (shed, threw, cast, put)', 'shed'),
                                                ('B2', 'His reckless behavior _______ serious consequences for the entire team. (had, made, took, gave)', 'had'),
                                                ('B2', 'The company decided to _______ its operations to reduce costs. (streamline, streamlined, streaming, streams)', 'streamline'),
                                                ('B2', 'The evidence _______ contradicted the suspect’s alibi. (strongly, weakly, barely, hardly)', 'strongly'),
                                                ('B2', 'The actor’s performance was _______ praised by critics. (widely, narrowly, shortly, briefly)', 'widely'),
                                                ('B2', 'The new law aims to _______ discrimination in the workplace. (prevent, promote, provoke, provide)', 'prevent'),
                                                ('B2', 'The restaurant’s menu _______ a wide variety of vegetarian options. (offers, proposes, suggests, presents)', 'offers'),
                                                ('B2', 'The company’s decision to downsize has _______ hundreds of jobs. (eliminated, elevated, elicited, elaborated)', 'eliminated'),
                                                ('B2', 'The author’s latest novel _______ mixed reviews from critics. (received, perceived, conceived, deceived)', 'received'),
                                                ('B2', 'The city council has _______ a new initiative to improve public transportation. (launched, lunched, lynched, leeched)', 'launched');
INSERT INTO tests (grade, question, answer) VALUES
                                                ('C1', 'The politician’s speech was filled with _______ rhetoric that appealed to emotions rather than reason. (inflammatory, inflationary, inflatable, infallible)', 'inflammatory'),
                                                ('C1', 'The company’s unethical practices have _______ its reputation in the industry. (tarnished, polished, burnished, furnished)', 'tarnished'),
                                                ('C1', 'The novel’s intricate plot _______ the reader’s attention from beginning to end. (captivated, captured, capitulated, catapulted)', 'captivated'),
                                                ('C1', 'The new tax law has created a _______ of loopholes for large corporations. (plethora, dearth, zenith, nadir)', 'plethora'),
                                                ('C1', 'The scientist’s groundbreaking research _______ conventional wisdom on climate change. (challenged, championed, channeled, chastised)', 'challenged'),
                                                ('C1', 'The company’s rapid expansion has led to a _______ in product quality. (deterioration, determination, detraction, detention)', 'deterioration'),
                                                ('C1', 'The critic’s scathing review _______ the artist’s latest work. (eviscerated, evacuated, evaluated, elevated)', 'eviscerated'),
                                                ('C1', 'The documentary _______ light on the insidious nature of modern surveillance. (shed, shred, shod, shad)', 'shed'),
                                                ('C1', 'The CEO’s decision to step down was _______ by a series of financial scandals. (precipitated, percolated, perpetrated, perpetuated)', 'precipitated'),
                                                ('C1', 'The author’s prose is known for its _______ style, often requiring multiple readings to fully grasp. (abstruse, obtuse, obtrusive, abstinent)', 'abstruse'),
                                                ('C1', 'The new legislation aims to _______ the power of tech monopolies. (curtail, curtain, curdle, cuddle)', 'curtail'),
                                                ('C1', 'The philosopher’s arguments were _______ in their logic, leaving no room for counterarguments. (impeccable, improbable, impenetrable, impertinent)', 'impeccable'),
                                                ('C1', 'The company’s innovative approach has _______ it from its competitors in the market. (distinguished, extinguished, relinquished, vanquished)', 'distinguished'),
                                                ('C1', 'The politician’s comments were seen as a _______ attempt to divert attention from the scandal. (transparent, translucent, transcendent, transient)', 'transparent'),
                                                ('C1', 'The artist’s latest work is a _______ commentary on modern consumer culture. (scathing, soothing, seething, scything)', 'scathing'),
                                                ('C1', 'The new urban development project has been _______ by local environmental groups. (lambasted, lampooned, lamented, laminated)', 'lambasted'),
                                                ('C1', 'The company’s financial report _______ a complex web of offshore accounts and tax avoidance schemes. (unveiled, unraveled, unfurled, unnerved)', 'unveiled'),
                                                ('C1', 'The diplomat’s _______ response to the crisis helped to defuse tensions between the two nations. (measured, metered, metered, mutated)', 'measured'),
                                                ('C1', 'The scientist’s hypothesis was _______ by years of meticulous research and experimentation. (bolstered, battered, bantered, bartered)', 'bolstered'),
                                                ('C1', 'The artist’s work is characterized by a _______ use of color and form, creating a sense of dynamism and movement. (vivid, vapid, volatile, viscous)', 'vivid');
INSERT INTO tests (grade, question, answer) VALUES
                                                ('C2', 'The politician’s rhetoric was so _______ that it left even his staunchest supporters questioning his sincerity. (mendacious, mendaciously, mendacity, mendacities)', 'mendacious'),
                                                ('C2', 'The author’s latest novel is a _______ exploration of the human psyche, delving into the deepest recesses of consciousness. (labyrinthine, labyrinthian, labyrinth, labyrinths)', 'labyrinthine'),
                                                ('C2', 'The critic’s review was so _______ that it effectively ended the playwright’s career. (vitriolic, vitreous, vitric, vitrescent)', 'vitriolic'),
                                                ('C2', 'The company’s financial stratagems were so _______ that they managed to evade detection for years. (Byzantine, Byzantium, Byzant, Byzantinism)', 'Byzantine'),
                                                ('C2', 'The philosopher’s arguments were characterized by a level of _______ that made them nearly impenetrable to the average reader. (abstruseness, abstrusion, abstruse, abstrusity)', 'abstruseness'),
                                                ('C2', 'The diplomat’s _______ response to the crisis was crucial in averting an international incident. (nuanced, nuance, nuancing, nuanceful)', 'nuanced'),
                                                ('C2', 'The artist’s work is known for its _______, blending elements of surrealism and abstract expressionism in a unique style. (idiosyncrasy, idiosyncratic, idiosyncratically, idiosyncrasy)', 'idiosyncrasy'),
                                                ('C2', 'The new legislation has been criticized for its _______, with detractors arguing that it leaves too much room for interpretation. (ambiguity, ambiguous, ambiguously, ambiguousness)', 'ambiguity'),
                                                ('C2', 'The CEO’s _______ management style has led to unprecedented growth, but also to high employee turnover. (Machiavellian, Machiavellianism, Machiavelli, Machiavellianist)', 'Machiavellian'),
                                                ('C2', 'The poet’s verses are renowned for their _______, often requiring multiple readings to fully appreciate their depth. (polysemy, polysemous, polysemically, polysemousness)', 'polysemy'),
                                                ('C2', 'The journalist’s exposé was a _______ piece of investigative reporting, uncovering layers of corruption. (tour de force, tour de france, tour de rol, tour de table)', 'tour de force'),
                                                ('C2', 'The company’s rapid expansion was _______ by a series of strategic acquisitions and mergers. (catalyzed, catalyze, catalyst, catalytic)', 'catalyzed'),
                                                ('C2', 'The actor’s performance was so _______ that it blurred the line between fiction and reality. (verisimilitudinous, verisimilitude, verisimilar, verisimilarily)', 'verisimilitudinous'),
                                                ('C2', 'The scientist’s theory, once considered _______, has now become widely accepted in the field. (heretical, heretically, heretic, hereticism)', 'heretical'),
                                                ('C2', 'The novel’s narrative structure is intentionally _______, challenging readers’ expectations of linear storytelling. (nonlinear, nonlinearity, nonlinearly, nonlinearness)', 'nonlinear'),
                                                ('C2', 'The politician’s speech was filled with _______, cleverly avoiding any concrete promises or commitments. (obfuscation, obfuscate, obfuscatory, obfuscatoriness)', 'obfuscation'),
                                                ('C2', 'The artist’s latest installation is a _______ commentary on the ephemeral nature of modern life. (poignant, poignancy, poignantly, poignantness)', 'poignant'),
                                                ('C2', 'The company’s decision to diversify its portfolio was a _______ move that ultimately saved it from bankruptcy. (prescient, prescience, presciently, prescientness)', 'prescient'),
                                                ('C2', 'The critic’s analysis of the film was _______ in its attention to detail, dissecting every aspect of the production. (meticulous, meticulousness, meticulously, meticulosity)', 'meticulous') ,
                                                ('C2', 'The philosopher’s treatise on ethics is considered a _______ work, fundamentally changing the field’s approach to moral reasoning. (seminal, seminary, seminar, seminally)', 'seminal');