POST localhost:8080/api/posts
content-type: application/json
Authorization: Basic hyezuu@naver.com qweqwe123

{
  "userId": 1,
  "title": "apple13",
  "content": "Content 1"
}


### get id
GET localhost:8080/api/posts/17

### get all
GET localhost:8080/api/posts

### get by keyword
GET localhost:8080/api/posts?keyword=apple

### update
PUT localhost:8080/api/posts/13
content-type: application/json
Authorization: Basic hyezuu@naver.com qweqwe123

{
    "title": "Post 1",
    "content": "Content dd1"
}

### delete
DELETE localhost:8080/api/posts/17
Authorization: Basic hyezuu@naver.com qweqwe123

### get my posts
GET localhost:8080/api/me/posts
Authorization: Basic hyezuu@naver.com qweqwe123