POST localhost:8080/api/signup
content-type: application/json

{
  "email": "duudu0704@gmail.com",
  "password": "qweqwe123",
  "nickname": "혜주2"
}

### get me
GET localhost:8080/api/me
Authorization: Basic hyezuu@naver.com qweqwe123

//default size = 20, page=0 부터 시작입니다 기본적으로 최신순 조회입니다 (최근에 추가된게 앞으로나와요!)
### get my voca
GET localhost:8080/api/me/vocabulary-list
Authorization: Basic hyezuu@naver.com qweqwe123

### get my voca (페이지네이션)
GET localhost:8080/api/me/vocabulary-list?page=0&size=10
Authorization: Basic hyezuu@naver.com qweqwe123

### post email verification (이메일 전송!)
POST localhost:8080/api/request-verification?email=duudu0704@gmail.com

### post email verification code (이메일, 인증코드 다시 응답하기)
POST localhost:8080/api/verify-email?email=duudu0704@gmail.com&code=253312

### get temp password (임시비밀번호 발급)
GET localhost:8080/api/auth/password?email=duudu0704@gmail.com

### check email (이메일 중복검사)
GET localhost:8080/api/email-duplication?email=hyezuu@naver.com

### check nickname
GET localhost:8080/api/nickname-duplication?nickname=혜주

### delete me
DELETE localhost:8080/api/withdrawal
Authorization: Basic hyezuu@naver.com qweqwe123