POST localhost:8080/api/signup
content-type: application/json

{
  "email": "hyezuu@naver.com",
  "password": "qweqwe123",
  "nickname": "혜주"
}


### get me
GET localhost:8080/api/me
Authorization: Basic hyezuu@naver.com qweqwe123

### check email
GET localhost:8080/api/email-duplication?email=hyezuu@naver.com

### check nickname
GET localhost:8080/api/nickname-duplication?nickname=혜주

### delete me
DELETE localhost:8080/api/withdrawal
Authorization: Basic hyezuu@naver.com qweqwe123